baseURL: 'https://blog.dalydays.com/'
title: Eric Daly's Blog
paginate: 10

theme: PaperModX
pygmentsUseClasses: true

markup:
  highlight:
    anchorLineNos: false
    codeFences: true
    guessSyntax: false
    hl_Lines: ""
    hl_inline: false
    lineAnchors: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: true
    noHl: false
    style: github
    tabWidth: 4

minify:
  disableXML: true
  minifyOutput: true
  paginate: 3
  languageCode: en-us
  DefaultContentLanguage: en-us
  enableInlineShortcodes: true
  footnoteReturnLinkContents: ^
#  custom_css: '[css/contactme.css]'

params:
  github: 'https://github.com/linucksrox'
  description: Sharing What I Know
  ShowBreadCrumbs: true
  ShowReadingTime: true
  ShowToc: true
  TocOpen: true
  ShowPostNavLinks: true
  ShowCodeCopyButtons: true
  comments: true
  mainSections:
    - post

menu:
  main:
    - identifier: archives
      name: Archives
      url: /archives/
      weight: 1
    - identifier: search
      name: Search
      url: /search/
      weight: 2
    - identifier: about
      name: About
      url: /about/
      weight: 10
    - identifier: contactme
      name: Contact
      url: /contactme/
      weight: 20
    - identifier: github-linucksrox
      name: Github
      url: 'https://github.com/linucksrox'
      weight: 30

taxonomies:
  category: categories
  tag: tags
  series: series

# for search
outputs:
  home:
    - HTML
    - JSON
